title: <p align="center"> Rahul Das </p>
logo: /assets/img/Firefly 20231109153505.png

description:
  <p align="center">
  <a href="/assets/img/Rahul_Das_Euromoniter.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahuldaskolkata/">LinkedIn</a> |
  <a href="https://github.com/rahuldaskolkata">GitHub</a>
  
  <br>   
  Aspiring Data Analyst with 2 years of experience in technical support and a strong foundation in data analysis and visualization. 
  Proficient in Python, SQL, and data manipulation. 
  Skilled in tools such as Tableau, Power BI, and Git-Hub. 
  Currently pursuing a Post Graduate Diploma in Data Science. 
  Dedicated to leveraging analytical skills to drive business insights and enhance decision-making processes.
  <br>
  </p>
  

theme: jekyll-theme-minimal
