title: <p align="center"> Rahul Das </p>
logo: /assets/img/Firefly 20231109153505.jpg

description:
  <p align="center">
  <a href="assets/img/Rahul_Das_Euromoniter.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahuldaskolkata/">LinkedIn</a> |
  <a href="https://github.com/rahuldaskolkata">GitHub</a>
  
  <br>   
  Aspiring Data Analyst with 2 years of experience in Technical Support and a strong foundation in data analysis and visualization.
  Proficient in Python, SQL, Advance Excel and data manipulation.
  Skilled in tools such as Tableau, Power BI and Git-Hub.
  Currently pursuing a Post Graduate Diploma in Data Science from IIIT-B.
  <br>
  </p>
  

theme: jekyll-theme-minimal
