title: <p align="center"> Rahul Das </p>
logo: /assets/img/Firefly 20231109153505.jpg

description:
  <p align="center">
  <a href="assets/img/Rahul_Das_Euromoniter.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahuldaskolkata/">LinkedIn</a> |
  <a href="https://github.com/rahuldaskolkata">GitHub</a>
  
  <br>   
  IIIT-B Certified Data Analytics professional with a strong foundation in data analysis and visualisation, 
  including proficiency in Python, SQL, data manipulation, Tableau, Power BI, AWS and GitHub. 
  With 2 years of experience in technical support and a recently completed Executive Post Graduate Program in Data Science.
  I am dedicated to leveraging my analytical skills to drive business insights and enhance decision-making processes.
  Currently seeking a position as a Data Analyst.
  <br>
  </p>
  

theme: jekyll-theme-minimal
