title: <p align="center"> Rahul Das </p>
logo: /assets/img/225.jpg

description:
  <p align="center">
  <a href="assets/img/Rahul_Das_Euromoniter.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahuldaskolkata/">LinkedIn</a> |
  <a href="https://github.com/rahuldaskolkata">GitHub</a>
  
  <br>   
IIIT-B certified Data Analytics professional with skills in Python, SQL, Tableau, Power BI, AWS, and GitHub. 
With 2 years of technical support experience and a recent Executive Post Graduate Program in Data Science, 
I aim to drive business insights and improve decision-making. Seeking a Data Analyst position.
  <br>
  </p>
  

theme: jekyll-theme-minimal
